<#
.SYNOPSIS
    Build VisualActor.rmskin from the Rainmeter skin sources.

.DESCRIPTION
    Thin wrapper that (1) regenerates Resources/variables.inc from
    config/rainmeter.yaml + RAINMETER_* environment variables so the packaged
    widget matches your config, then (2) delegates to scripts/package_rmskin.ps1
    to produce a valid .rmskin (ZIP + Rainmeter footer).

.EXAMPLE
    pwsh ./build_rainmeter_skin.ps1
    powershell -ExecutionPolicy Bypass -File .\build_rainmeter_skin.ps1
#>
param(
    [string]$OutFile = (Join-Path $PSScriptRoot "VisualActor.rmskin")
)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$varsInc = Join-Path $root "rainmeter\VisualActor\Resources\variables.inc"

function Get-EnvOrDefault($name, $default) {
    $v = [System.Environment]::GetEnvironmentVariable($name)
    if ([string]::IsNullOrWhiteSpace($v)) { return $default } else { return $v }
}

# Resolve widget settings (env overrides defaults; mirrors config/rainmeter.yaml).
$serverUrl = Get-EnvOrDefault "RAINMETER_SERVER_URL" "http://127.0.0.1:8765/rainmeter"
$width     = Get-EnvOrDefault "RAINMETER_WIDTH"  "480"
$height    = Get-EnvOrDefault "RAINMETER_HEIGHT" "640"
$opacity   = Get-EnvOrDefault "RAINMETER_OPACITY" "255"
$click     = Get-EnvOrDefault "RAINMETER_CLICK_THROUGH" "0"
$ontop     = Get-EnvOrDefault "RAINMETER_ALWAYS_ON_TOP" "1"
$mode      = Get-EnvOrDefault "RAINMETER_WIDGET_MODE" "reactor"

Write-Output "Regenerating variables.inc (Width=$width Height=$height URL=$serverUrl)"
$healthUrl = ($serverUrl -replace "/rainmeter/?$", "/health")
@"
[Variables]
; ---- Visual Actor widget variables (generated by build_rainmeter_skin.ps1) ----
ServerURL=$serverUrl
ServerHealthURL=$healthUrl

; Widget visual mode: "reactor" (arc-reactor visualizer) or "face" (avatar)
WidgetMode=$mode

; Geometry
Width=$width
Height=$height

; Appearance (0-255)
Opacity=$opacity
Transparent=1

; Interaction toggles (0/1)
ClickThrough=$click
AlwaysOnTop=$ontop
Draggable=1

; Refresh cadence
RefreshMs=1000
StatusPollMs=3000

; PowerShell helpers
ServerStart=#@#launch_server.ps1
ServerStop=#@#stop_server.ps1
ServerCheck=#@#check_server.ps1
"@ | Set-Content -Encoding UTF8 $varsInc

& (Join-Path $root "scripts\package_rmskin.ps1") -OutFile $OutFile
Write-Output "Done."
